name: Extension Bundling

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug


jobs:
  build:
    name: Extension Bundling Check
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.2

      - name: Build with Pixi
        run: pixi run build

      - name: Upload build artifact
        if: ${{ success() && github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts-for-update-site-${{ github.run_id }}
          path: local-update-site
          retention-days: 1


  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - name: Write run summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Event | ${{ github.event_name }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Log Level | ${{ github.event.inputs.logLevel || 'n/a' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Ref | ${{ github.ref }} |" >> $GITHUB_STEP_SUMMARY
          echo "| SHA | ${{ github.sha }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artifacts" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Artifact (only on manual runs): extension-artifacts-for-update-site-${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "No artifact uploaded for non-manual runs." >> $GITHUB_STEP_SUMMARY
          fi
